run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gochecknoinits
    - govet
    - ineffassign
    - lll
    - noctx
    - staticcheck
    - unused

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    # Exclude gochecknoinits from main packages where it's common for setup.
    - path: "cmd/mcp_start.go"
      linters:
        - "gochecknoinits"
    - path: "mcp/server.go"
      linters:
        - "gochecknoinits"
