# golangci-lint configuration
# Documentation: https://golangci-lint.run/usage/configuration/

# Absolute bare-bones configuration to bypass strict schema validation errors in CI.
# This enables only a few core linters without any custom settings, exclusions, or other sections.

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
