# GoReleaser configuration for mongo-migration
# Documentation: https://goreleaser.com
version: 2

project_name: mongo-migration-tool

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: mongo-migration
    binary: mongo-migration
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: default
    format: tar.gz
    # Windows should use zip
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - readme.md
      - LICENSE
      - mcp.md
      - .env.example
      - examples/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^refactor:'
      - '^style:'
      - '^build:'
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'MCP Integration'
      regexp: '^.*?mcp(\(.+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

brews:
  - name: mongo-migration
    repository:
      owner: drewjocham
      name: homebrew-mongo-migration
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    

    directory: Formula
    homepage: https://github.com/drewjocham/mongo-migration-tool
    description: "MongoDB migration tool with and MCP support"
    license: MIT
    dependencies:
      - name: mongodb/brew/mongodb-community
        type: optional

    install: |-
      bin.install "mongo-migration"
      
      # Install example configurations
      pkgshare.install ".env.example"
      pkgshare.install "examples"
      pkgshare.install "MCP.md"

    test: |
      system "#{bin}/mongo-migration --version"
dockers:
  - image_templates:
      - "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}-amd64"
      - "ghcr.io/drewjocham/mongo-migration-tool:latest-amd64"
    dockerfile: docker/Dockerfile.release
    use: buildx
    ids:
      - mongo-migration
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/drewjocham/mongo-migration-tool"
      - "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}-arm64"
      - "ghcr.io/drewjocham/mongo-migration-tool:latest-arm64"
    dockerfile: docker/Dockerfile.release
    use: buildx
    ids:
      - mongo-migration
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/drewjocham/mongo-migration-tool"
    extra_files:
      - go.mod
      - go.sum

docker_manifests:
  - name_template: "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}"
    image_templates:
      - "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}-amd64"
      - "ghcr.io/drewjocham/mongo-migration-tool:{{ .Version }}-arm64"
  
  - name_template: "ghcr.io/drewjocham/mongo-migration-tool:latest"
    image_templates:
      - "ghcr.io/drewjocham/mongo-migration-tool:latest-amd64"
      - "ghcr.io/drewjocham/mongo-migration-tool:latest-arm64"

release:
  github:
    owner: drewjocham
    name: mongo-migration-tool
  replace_existing_artifacts: true
  
  draft: false
  prerelease: auto
  
  name_template: "Release v{{.Version}}"

  header: |
    
    Generated by GoReleaser for {{.ProjectName}}
    
    Happy to share the latest release of the MongoDB Migration Tool. 
    
    ### Getting Started

    It's easy to get started with the MongoDB Migration Tool. Just follow the installation instructions 
    below and run the `init` command to create a new configuration file.

    ```sh
    mongo-migration init
    ```

    ### Installation

    #### Homebrew (macOS/Linux)
    ```bash
    brew tap drewjocham/mongo-migration
    brew install mongo-migration
    ```

    #### Go Install
    ```bash
    go install github.com/drewjocham/mongo-migration-tool@v{{.Version}}
    ```

    #### Docker
    ```bash
    docker run --rm -v $(pwd):/app ghcr.io/drewjocham/mongo-migration-tool:{{.Version}} --help
    ```

    We welcome your feedback and contributions. Please feel free to open an issue or pull request on our [GitHub repository](https://github.com/drewjocham/mongo-migration-tool).
  
  footer: |
    ## Thank You!

    Thank you for trying out the MongoDB Migration Tool.
    
    For more detailed information, please see the [documentation](https://pkg.go.dev/github.com/drewjocham/mongo-migration-tool).

nfpms:
  - id: packages
    package_name: mongo-migration
    
    homepage: https://github.com/drewjocham/mongo-migration-tool
    description: MongoDB migration tool with MCP support
    maintainer: Drew Jocham <mongo@jocham.io>
    license: MIT
    
    formats:
      - deb
      - rpm
      - apk
    
    bindir: /usr/bin

announce:
  skip: true
