# Configuration consumed by the SLSA Go builder workflow.
version: 1

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

dir: ./cmd
main: .
binary: mongo-migration-{{ .Os }}-{{ .Arch }}

goos: linux
goarch: amd64

ldflags:
  - -s -w
  - -X main.version={{ .Env.VERSION }}
  - -X main.commit={{ .Env.COMMIT }}
  - -X main.date={{ .Env.BUILD_DATE }}
  - -X main.builtBy=slsa-github-generator
